export * from './errores.js';
export * from './Identificador.js';
export * from './Email.js';
export * from './Telefono.js';
export * from './Hora.js';
export * from './fechas.js';
export * from './FechaLocal.js';
export * from './ZonaHoraria.js';
export * from './AutorizacionDeDatos.js';
